name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["main", "master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    timeout-minutes: 90
    strategy:
      matrix:
        os: [linux-gnu, macos-none]
        arch: [x86_64, arm64]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ziglang/zig-bootstrap
          ref: c46035de775405d0916e227528f24a78c3c2391d
      - uses: actions/checkout@v3
        with:
          path: zig
      - name: Run
        run: |
          ./build -j$(ncpus) ${{matrix.arch}}-${{matrix.os}} baseline
          mv out/${{matrix.arch}}-${{matrix.os}} /tmp/zig
      - uses: actions/upload-artifact@v3
        name: Upload
        with:
          name: zig-${{matrix.os}}-${{matrix.arch}}
          path: /tmp/zig
  release:
    name: Release
    runs-on: ubuntu-18.04
    timeout-minutes: 90
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: zig-linux-gnu-x86_64
          path: /tmp/zig-linux-gnu-x86_64/zig.zip
      - uses: actions/download-artifact@v3
        with:
          name: zig-linux-gnu-aarch64
          path: /tmp/zig-linux-gnu-aarch64/zig.zip
      - uses: actions/download-artifact@v3
        with:
          name: zig-macos-none-x86_64
          path: /tmp/zig-macos-none-x86_64/zig.zip
      - uses: actions/download-artifact@v3
        with:
          name: zig-macos-none-aarch64
          path: /tmp/zig-macos-none-aarch64/zig.zip
      - name: convert
        run: |
          cd /tmp/zig-linux-gnu-x86_64
          unzip zig-linux-gnu-x86_64.zip
          tar -czf zig-linux-gnu-x86_64.tar.gz zig

          cd /tmp/zig-linux-gnu-aarch64
          unzip zig-linux-gnu-aarch64.zip
          tar -czf zig-linux-gnu-aarch64.tar.gz zig

          cd /tmp/zig-macos-none-x86_64
          unzip zig-macos-none-x86_64.zip
          tar -czf zig-macos-none-x86_64.tar.gz zig

          cd /tmp/zig-macos-none-aarch64
          unzip zig-macos-none-aarch64.zip
          tar -czf zig-macos-none-aarch64.tar.gz zig

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest"
          files: |
            - /tmp/zig-linux-gnu-x86_64/zig-linux-gnu-x86_64.tar.gz
            - /tmp/zig-linux-gnu-aarch64/zig-linux-gnu-aarch64.tar.gz
            - /tmp/zig-macos-none-x86_64/zig-macos-none-x86_64.tar.gz
            - /tmp/zig-macos-none-aarch64/zig-macos-none-aarch64.tar.gz
