name: ci
on:
  pull_request:
  push:
    branches:
      - master
      - llvm19
      - 014-dev
      - actions-test
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
permissions:
  # Sets permission policy for `GITHUB_TOKEN`
  contents: read
jobs:
  build:
    runs-on: big-ubuntu
    strategy:
      matrix:
        target:
          - x86_64-macos-none
          - x86_64-linux-musl
          - x86_64-windows-gnu
          - aarch64-macos-none
          - aarch64-linux-musl
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ziglang/zig-bootstrap
          ref: 50d8e88ba329b5d58a212f9fd2e9b1ad59a88e7d
      - run: rm -rf zig
      - uses: actions/checkout@v4
        with:
          path: zig
      - run: CMAKE_GENERATOR=Ninja ./build ${{ matrix.target }} baseline
      - uses: actions/upload-artifact@v4
        with:
          name: bootstrap-${{ matrix.target }}
          path: out

# a second step can download all the bootstrap results, add zls, and create the release
# - uses: actions/checkout@v4
#   with:
#     repository: zigtools/zls
#     ref: d3d11a089d608014d50aca429fcb8bd82724fedf
#     path: zls
# - run: cd zls && zig build -Doptimize=ReleaseSafe -Dtarget=${{ matrix.target }}
# - run: cp zls/zig-out/bin/zls out/zig-${{ matrix.target }}-baseline/zls